name: Deploy MindModel to Docker Host

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_HOST: 10.11.2.6
  RUNNER_USER: jaal
  SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy MindModel
      env:
        SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      run: |
        chmod +x scripts/deploy_docker.sh
        echo "$SUDO_PASSWORD" | ./scripts/deploy_docker.sh
        
    - name: Show final status
      run: |
        echo "🎉 Deployment completed!"
        echo ""
        echo "📋 Service URLs:"
        echo "  - Main API: http://10.11.2.6:8001"
        echo "  - Health Check: http://10.11.2.6:8001/health"
        echo "  - Status: http://10.11.2.6:8001/status"
        echo ""
        echo "📋 Container Info:"
        docker ps | grep mindmodel
